apiVersion: v1
kind: Pod
metadata:
  labels:
    agent: zeebe-ci-build
spec:
  nodeSelector:
    cloud.google.com/gke-nodepool: slaves
  tolerations:
    - key: "slaves"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
    - name: maven
      image: maven:3.6.0-jdk-8
      command: ["cat"]
      tty: true
      env:
        - name: JAVA_TOOL_OPTIONS
          value: |
            -XX:+UseContainerSupport
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 1
          memory: 2Gi
    - name: dind
      image: docker:18.09.4-dind
      args: ["--storage-driver=overlay2"]
      tty: true
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: 6
          memory: 8Gi
        requests:
          cpu: 6
          memory: 8Gi
